language: node_js
node_js:
    - node
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgtk2.0-0 libgconf-2-4 libasound2 libxtst6 libxss1 libnss3 xvfb g++
  - npm install -g node-gyp
